name: Pulumi
permissions:
    id-token: write
    contents: read
on:
  push:
    branches:
      - main
jobs:
  up:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: true
      - uses: actions/setup-node@v1
        with:
          node-version: 21.x
    #   - name: Configure AWS Credentials (IAM User)
    #     uses: aws-actions/configure-aws-credentials@v4
    #     with:
    #       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #       aws-region: eu-west-1
        #   aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.AWS_ASSUME_ROLE}}
          role-session-name: aws-access-test-session
          aws-region: eu-west-1
      - run: npm ci
      - uses: pulumi/actions@v5
        with:
          command: up
          stack-name: dev
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
